let questions= [
    { phobia : "Aerophobia",
        choiceA : {name:"Flying", icon:'<i class="fas fa-plane"></i>'},
        choiceB : {name:"Amphibians", icon:'<i class="fas fa-frog"></i>'},
        choiceC : {name:"Insects", icon:'<i class="fas fa-bug"></i>'},
        choiceD : {name:"Being touched", icon:'<i class="fas fa-hand-paper"></i>'},
        correct:"A",
},
{ phobia : "Arachnophobia",
choiceA : {name:"Horses", icon:'<i class="fas fa-horse"></i>'},
choiceB : {name:"Spiders", icon:'<i class="fas fa-spider"></i>'},
choiceC: {name:"Technology", icon:'<i class="fas fa-sim-card"></i>'},
choiceD: {name:"Trees", icon:'<i class="fas fa-tree"></i>'},
correct:"B",
}, 
{ phobia : "Aichmophobia",
choiceA : {name:"Books", icon:'<i class="fas fa-book-open"></i>'},
choiceB : {name:"Doctors", icon:'<i class="fas fa-user-md"></i>'},
choiceC: {name:"Needles", icon:'<i class="fas fa-syringe"></i>'},
choiceD: {name:"Buttons", icon :'<i class="fas fa-toggle-on"></i>'},
correct:"C",
},
{ phobia : "Androphobia",
choiceA : {name:"Dentists", icon:'<i class="fas fa-tooth"></i>'},
choiceB : {name:"Insects", icon:'<i class="fas fa-bug"></i>'},
choiceC: {name:"Witches", icon:'<i class="fas fa-hat-wizard"></i>'},
choiceD: {name:"Men", icon:'<i class="fas fa-male"></i>'},
correct:"D",
},
{ phobia : "Anthrophobia",
choiceA : {name:"Flowers", icon:'<i class="fas fa-spa"></i>'},
choiceB : {name:"Trees", icon:'<i class="fas fa-tree"></i>'},
choiceC: {name:"Technology", icon:'<i class="fas fa-sim-card"></i>'},
choiceD: {name:"Computers", icon:'<i class="fas fa-desktop"></i>'},
correct:"A",
},
{ phobia : "Anthropophobia",
choiceA : {name:"Flowers", icon:'<i class="fas fa-spa"></i>'},
choiceB : {name:"People", icon:'<i class="fas fa-users"></i>'},
choiceC: {name:"Injections", icon:'<i class="fas fa-syringe"></i>'},
choiceD: {name:"Blood", icon:'<i class="fas fa-tint"></i>'},
correct : "B",
},
{ phobia : "Aphenphosmphobia",
choiceA : {name:"Horses", icon:'<i class="fas fa-horse"></i>'},
choiceB : {name:"Buttons", icon :'<i class="fas fa-toggle-on"></i>'},
choiceC: {name:"Being touched", icon:'<i class="fas fa-hand-paper"></i>'},
choiceD: {name:"Germs", icon:'<i class="fas fa-viruses"></i>'},
correct: "C"
},
{ phobia : "Astraphobia",
choiceA : {name:"Dogs", icon:'<i class="fas fa-dog"></i>'},
choiceB : {name:"Insects", icon:'<i class="fas fa-bug"></i>'},
choiceC: {name:"Flying", icon:'<i class="fas fa-plane"></i>'},
choiceD: {name:"Thunder and Lightening", icon:'<i class="fas fa-bolt"></i>'},
correct:"D",
},
{ phobia : "Bacteriophobia ",
choiceA : {name:"Bacteria", icon:'<i class="fas fa-bacterium"></i>'},
choiceB : {name:"Cats", icon:'<i class="fas fa-cat"></i>'},
choiceC: {name:"Witches", icon:'<i class="fas fa-hat-wizard"></i>'},
choiceD: {name:"Ugliness", icon:'<i class="fas fa-frown-open"></i>'},
correct:"A",
},
{ phobia : "Batrachophobia",
choiceA : {name:"Technology", icon:'<i class="fas fa-sim-card"></i>'},
choiceB : {name:"Amphibians", icon:'<i class="fas fa-frog"></i>'},
choiceC: {name:"Speed", icon:'<i class="fas fa-tachometer-alt"></i>'},
choiceD: {name:"Bacteria", icon:'<i class="fas fa-bacterium"></i>'},
correct:"B",
},
{ phobia : "Bibliophobia",
choiceA : {name:"Clocks", icon:'<i class="far fa-clock"></i>'},
choiceB : {name:"Blood", icon:'<i class="fas fa-tint"></i>'},
choiceC: {name:"Books", icon:'<i class="fas fa-book-open"></i>'},
choiceD: {name:"Germs", icon:'<i class="fas fa-viruses"></i>'},
correct:"C",
},
{ phobia : "Botanophobia",
choiceA : {name:"Dentists", icon:'<i class="fas fa-tooth"></i>'},
choiceB : {name:"The Colour White", icon:'<i class="far fa-square"></i>'},
choiceC: {name:"Speed", icon:'<i class="fas fa-tachometer-alt"></i>'},
choiceD: {name:"Plants", icon:'<i class="fas fa-seedling"></i>'},
correct:"D",
},
{ phobia : "Cacophobia",
choiceA : {name:"Ugliness", icon:'<i class="fas fa-frown-open"></i>'},
choiceB : {name:"Computers", icon:'<i class="fas fa-desktop"></i>'},
choiceC: {name:"ferns", icon:'<i class="fab fa-pagelines"></i>'},
choiceD: {name:"Amphibians", icon:'<i class="fas fa-frog"></i>'},
correct:"A",
},
{ phobia : "Chionophobia",
choiceA : {name:"Doctors", icon:'<i class="fas fa-user-md"></i>'},
choiceB : {name:"Snow", icon:'<i class="fas fa-snowflake"></i>'},
choiceC: {name:"The Moon", icon:'<i class="far fa-moon"></i>'},
choiceD: {name:"Ugliness", icon:'<i class="fas fa-frown-open"></i>'},
correct:"B",
},
{ phobia : "Chronomentrophobia",
choiceA : {name:"Blood", icon:'<i class="fas fa-tint"></i>'},
choiceB : {name:"Injections", icon:'<i class="fas fa-syringe"></i>'},
choiceC: {name:"Clocks", icon:'<i class="far fa-clock"></i>'},
choiceD: {name:"The Colour White", icon:'<i class="far fa-square"></i>'},
correct:"C",
},
{ phobia : "Cyberphobia",
choiceA : {name:"Snow", icon:'<i class="fas fa-snowflake"></i>'},
choiceB : {name:"Children", icon:'<i class="fas fa-child"></i>'},
choiceC: {name:"Men", icon:'<i class="fas fa-male"></i>'},
choiceD: {name:"Computers", icon:'<i class="fas fa-desktop"></i>'},
correct:"D",
},
{ phobia : "Cynophobia",
choiceA : {name:"Dogs", icon:'<i class="fas fa-dog"></i>'},
choiceB : {name:"Water", icon:'<i class="fas fa-water"></i>'},
choiceC: {name:"Birds", icon:'<i class="fas fa-crow"></i>'},
choiceD: {name:"Trees", icon:'<i class="fas fa-tree"></i>'},
correct:"A",
},
{ phobia : "Dendrophobia",
choiceA : {name:"Children", icon:'<i class="fas fa-child"></i>'},
choiceB : {name:"Trees", icon:'<i class="fas fa-tree"></i>'},
choiceC: {name:"School", icon:'<i class="fas fa-school"></i>'},
choiceD: {name:"Dentists", icon:'<i class="fas fa-tooth"></i>'},
correct:"B",
},
{ phobia : "Dentophobia",
choiceA : {name:"Plants", icon:'<i class="fas fa-seedling"></i>'},
choiceB : {name:"Speed", icon:'<i class="fas fa-tachometer-alt"></i>'},
choiceC: {name:"Dentists", icon:'<i class="fas fa-tooth"></i>'},
choiceD: {name:"Flying", icon:'<i class="fas fa-plane"></i>'},
correct:"C",
},
{ phobia : "Domatophobia",
choiceA : {name:"Being touched", icon:'<i class="fas fa-hand-paper"></i>'},
choiceB : {name:"Dogs", icon:'<i class="fas fa-dog"></i>'},
choiceC: {name:"People", icon:'<i class="fas fa-users"></i>'},
choiceD: {name:"Houses", icon:'<i class="fas fa-home"></i>'},
correct:"D",
},

{ phobia : "Elurophobia",
choiceA : {name:"Cats", icon:'<i class="fas fa-cat"></i>'},
choiceB : {name:"Doctors", icon:'<i class="fas fa-user-md"></i>'},
choiceC: {name:"ferns", icon:'<i class="fab fa-pagelines"></i>'},
choiceD: {name:"Bacteria", icon:'<i class="fas fa-bacterium"></i>'},
correct:"A",
},
{ phobia : "Entomophobia",
choiceA : {name:"Horses", icon:'<i class="fas fa-horse"></i>'},
choiceB : {name:"Insects", icon:'<i class="fas fa-bug"></i>'},
choiceC: {name:"Birds", icon:'<i class="fas fa-crow"></i>'},
choiceD: {name:"The Sun", icon:'<i class="fas fa-sun"></i>'},
correct:"B",
},
{ phobia : "Equinophobia",
choiceA : {name:"Water", icon:'<i class="fas fa-water"></i>'},
choiceB : {name:"Marraige", icon:'<i class="fas fa-ring"></i>'},
choiceC: {name:"Horses", icon:'<i class="fas fa-horse"></i>'},
choiceD: {name:"The Moon", icon:'<i class="far fa-moon"></i>'},
correct:"C",
},
{ phobia : "Gamophobia",
choiceA : {name:"Books", icon:'<i class="fas fa-book-open"></i>'},
choiceB : {name:"Cats", icon:'<i class="fas fa-cat"></i>'},
choiceC: {name:"Birds", icon:'<i class="fas fa-crow"></i>'},
choiceD: {name:"Marraige", icon:'<i class="fas fa-ring"></i>'},
correct:"D",
},
{ phobia : "Gynophobia",
choiceA : {name:"Women", icon:'<i class="fas fa-female"></i>'},
choiceB : {name:"Children", icon:'<i class="fas fa-child"></i>'},
choiceC: {name:"The Colour Black", icon:'<i class="fas fa-square"></i>'},
choiceD: {name:"Amphibians", icon:'<i class="fas fa-frog"></i>'},
correct:"A",
},
{ phobia : "Heliophobia ",
choiceA : {name:"Plants", icon:'<i class="fas fa-seedling"></i>'},
choiceB : {name:"The Sun", icon:'<i class="fas fa-sun"></i>'},
choiceC: {name:"Injections", icon:'<i class="fas fa-syringe"></i>'},
choiceD: {name:"Men", icon:'<i class="fas fa-male"></i>'},
correct:"B",
},
{ phobia : "Hemophobia",
choiceA : {name:"ferns", icon:'<i class="fab fa-pagelines"></i>'},
choiceB : {name:"Spiders", icon:'<i class="fas fa-spider"></i>'},
choiceC: {name:"Blood", icon:'<i class="fas fa-tint"></i>'},
choiceD: {name:"The Colour White", icon:'<i class="far fa-square"></i>'},
correct:"C",
},
{ phobia : "Hydrophobia",
choiceA : {name:"Being touched", icon:'<i class="fas fa-hand-paper"></i>'},
choiceB : {name:"Sleep", icon:'<i class="fas fa-bed"></i>'},
choiceC: {ame:"People", icon:'<i class="fas fa-users"></i>'},
choiceD: {name:"Water", icon:'<i class="fas fa-water"></i>'},
correct:"D",
},
{ phobia : "Iatrophobia",
choiceA : {name:"Doctors", icon:'<i class="fas fa-user-md"></i>'},
choiceB : {name:"Marraige", icon:'<i class="fas fa-ring"></i>'},
choiceC: {name:"Snow", icon:'<i class="fas fa-snowflake"></i>'},
choiceD: {name:"Needles", icon:'<i class="fas fa-syringe"></i>'},
correct:"A",
},
{ phobia : "Koumpounophobia",
choiceA : {name:"The Sun", icon:'<i class="fas fa-sun"></i>'},
choiceB : {name:"Buttons", icon :'<i class="fas fa-toggle-on"></i>'},
choiceC: {name:"The Colour Black", icon:'<i class="fas fa-square"></i>'},
choiceD: {name:"Plants", icon:'<i class="fas fa-seedling"></i>'},
correct:"B",
},
{ phobia : "Leukophobia",
choiceA : {name:"The Sun", icon:'<i class="fas fa-sun"></i>'},
choiceB : {name:"Flying", icon:'<i class="fas fa-plane-departure"></i>'},
choiceC: {name:"The Colour White", icon:'<i class="far fa-square"></i>'},
choiceD: {name:"Thunder", icon:'<i class="fas fa-cloud-showers-heavy"></i>'},
correct:"C",
},
{ phobia : "Megalophobia",
choiceA : {name:"Bacteria", icon:'<i class="fas fa-bacterium"></i>'},
choiceB : {name:"The Colour Black", icon:'<i class="fas fa-square"></i>'},
choiceC: {name:"Water", icon:'<i class="fas fa-water"></i>'},
choiceD: {name:"Large Things", icon:'<i class="fas fa-search-plus"></i>'},
correct:"D",
},
{ phobia : "Melanophobia ",
choiceA : {name:"The Colour Black", icon:'<i class="fas fa-square"></i>'},
choiceB : {name:"Houses", icon:'<i class="fas fa-home"></i>'},
choiceC: {name:"Germs", icon:'<i class="fas fa-head-side-cough"></i>'},
choiceD: {name:"Books", icon:'<i class="fas fa-book-open"></i>'},
correct:"A",
},
{ phobia : "Microphobia ",
choiceA : {name:"Kissing", icon:'<i class="far fa-kiss"></i>'},
choiceB : {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
choiceC: {name:"Sleep", icon:'<i class="fas fa-bed"></i>'},
choiceD: {name:"Snow", icon:'<i class="fas fa-snowflake"></i>'},
correct:"B",
},
{ phobia : "Mysophobia",
choiceA : {name:"Ugliness", icon:'<i class="fas fa-frown-open"></i>'},
choiceB : {name:"Flying", icon:'<i class="fas fa-plane-departure"></i>'},
choiceC: {name:"Germs", icon:'<i class="fas fa-head-side-cough"></i>'},
choiceD: {name:"Marraige", icon:'<i class="fas fa-ring"></i>'},
correct:"C",
},
{ phobia : "Noctiphobia",
choiceA : {name:"Thunder", icon:'<i class="fas fa-cloud-showers-heavy"></i>'},
choiceB : {name:"Flying", icon:'<i class="fas fa-plane"></i>'},
choiceC: {name:"Large Things", icon:'<i class="fas fa-search-plus"></i>'},
choiceD: {name:"Night", icon:'<i class="fas fa-moon"></i>'},
correct:"D",
},

{ phobia : "Nosocomephobia",
choiceA : {name:"Hospitals", icon:'<i class="fas fa-hospital"></i>'},
choiceB : {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
choiceC: {name:"Thunder and Lightening", icon:'<i class="fas fa-bolt"></i>'},
choiceD: {name:"Germs", icon:'<i class="fas fa-head-side-cough"></i>'},
correct:"A",
},
{ phobia : "Ombrophobia",
choiceA : {name:"Disease", icon:'<i class="fas fa-disease"></i>'},
choiceB : {name:"Rain", icon:'<i class="fas fa-cloud-rain"></i>'},
choiceC: {name:"Dogs", icon:'<i class="fas fa-dog"></i>'},
choiceD: {name:"Men", icon:'<i class="fas fa-male"></i>'},
correct:"B",
},
{ phobia : "Ornithophobia",
choiceA : {name:"Horses", icon:'<i class="fas fa-horse"></i>'},
choiceB : {name:"Being Stared at", icon:'<i class="fas fa-eye"></i>'},
choiceC: {name:"Birds", icon:'<i class="fas fa-crow"></i>'},
choiceD: {name:"Large Things", icon:'<i class="fas fa-search-plus"></i>'},
correct:"C",
},
{ phobia : "Papyrophobia",
choiceA : {name:"People", icon:'<i class="fas fa-users"></i>'},
choiceB : {name:"Disease", icon:'<i class="fas fa-disease"></i>'},
choiceC: {name:"Cats", icon:'<i class="fas fa-cat"></i>'},
choiceD: {name:"Paper", icon:'<i class="far fa-sticky-note"></i>'},
correct:"D",
},
{ phobia : "Pathophobia",
choiceA : {name:"Disease", icon:'<i class="fas fa-disease"></i>'},
choiceB : {name:"Night", icon:'<i class="fas fa-moon"></i>'},
choiceC: {name:"Computers", icon:'<i class="fas fa-desktop"></i>'},
choiceD: {name:"Clocks", icon:'<i class="far fa-clock"></i>'},
correct:"A",
},
{ phobia : "Pedophobia",
choiceA : {name:"Paper", icon:'<i class="far fa-sticky-note"></i>'},
choiceB : {name:"Children", icon:'<i class="fas fa-child"></i>'},
choiceC: {name:"Halloween", icon:'<i class="fas fa-ghost"></i>'},
choiceD: {name:"Flowers", icon:'<i class="fas fa-spa"></i>'},
correct:"B",
},
{ phobia : "Philematophobia ",
choiceA : {name:"Spiders", icon:'<i class="fas fa-spider"></i>'},
choiceB : {name:"Love", icon:'<i class="far fa-heart"></i>'},
choiceC: {name:"Kissing", icon:'<i class="far fa-kiss"></i>'},
choiceD: {name:"Sleep", icon:'<i class="fas fa-bed"></i>'},
correct:"C",
},
{ phobia : "Philophobia",
choiceA : {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
choiceB : {name:"Kissing", icon:'<i class="far fa-kiss"></i>'},
choiceC: {name:"Germs", icon:'<i class="fas fa-head-side-cough"></i>'},
choiceD: {name:"Love", icon:'<i class="far fa-heart"></i>'},
correct:"D",
},
{ phobia : "Podophobia",
choiceA : {name:"Feet", icon:'<i class="fas fa-socks"></i>'},
choiceB : {name:"The Moon", icon:'<i class="far fa-moon"></i>'},
choiceC: {name:"Halloween", icon:'<i class="fas fa-ghost"></i>'},
choiceD: {name:"Clocks", icon:'<i class="far fa-clock"></i>'},
correct:"A",
},
{ phobia : "Pteridophobia",
choiceA : {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
choiceB : {name:"ferns", icon:'<i class="fab fa-pagelines"></i>'},
choiceC: {name:"Halloween", icon:'<i class="fas fa-ghost"></i>'},
choiceD: {name:"Houses", icon:'<i class="fas fa-home"></i>'},
correct:"B",
},
{ phobia : "Pteromerhanophobia",
choiceA : {name:"Thunder and Lightening", icon:'<i class="fas fa-bolt"></i>'},
choiceB : {name:"Feet", icon:'<i class="fas fa-socks"></i>'},
choiceC: {name:"Flying", icon:'<i class="fas fa-plane-departure"></i>'},
choiceD: {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
correct:"C",
},
{ phobia : "Pyrophobia",
choiceA : {name:"Paper", icon:'<i class="far fa-sticky-note"></i>'},
choiceB : {name:"Needles", icon:'<i class="fas fa-syringe"></i>'},
choiceC: {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
choiceD: {name:"Fire", icon: '<i class="fas fa-fire"></i>'},
correct:"D",
},
{ phobia : "Samhainophobia",
choiceA : {name:"Halloween", icon:'<i class="fas fa-ghost"></i>'},
choiceB : {name:"Rain", icon:'<i class="fas fa-cloud-rain"></i>'},
choiceC: {name:"Feet", icon:'<i class="fas fa-socks"></i>'},
choiceD: {name:"Night", icon:'<i class="fas fa-moon"></i>'},
correct:"A",
},
{ phobia : "Scolionophobia",
choiceA : {name:"Germs", icon:'<i class="fas fa-viruses"></i>'},
choiceB : {name:"School", icon:'<i class="fas fa-school"></i>'},
choiceC: {name:"Disease", icon:'<i class="fas fa-disease"></i>'},
choiceD: {name:"Buttons", icon :'<i class="fas fa-toggle-on"></i>'},
correct:"B",
},
{ phobia : "Scoptophobia",
choiceA : {name:"Thunder", icon:'<i class="fas fa-cloud-showers-heavy"></i>'},
choiceB : {name:"Horses", icon:'<i class="fas fa-horse"></i>'},
choiceC: {name:"Being Stared at", icon:'<i class="fas fa-eye"></i>'},
choiceD: {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
correct:"C",
},
{ phobia : "Selenophobia",
choiceA : {name:"Paper", icon:'<i class="far fa-sticky-note"></i>'},
choiceB : {name:"Feet", icon:'<i class="fas fa-socks"></i>'},
choiceC: {name:"Flowers", icon:'<i class="fas fa-spa"></i>'},
choiceD: {name:"The Moon", icon:'<i class="far fa-moon"></i>'},
correct:"D"
},
{ phobia : "Somniphobia",
choiceA : {name:"Sleep", icon:'<i class="fas fa-bed"></i>'},
choiceB : {name:"Love", icon:'<i class="far fa-heart"></i>'},
choiceC: {name:"Halloween", icon:'<i class="fas fa-ghost"></i>'},
choiceD: {name:"Rain", icon:'<i class="fas fa-cloud-rain"></i>'},
correct:"A",
},
{ phobia : "Tachophobia",
choiceA : {name:"Fire", icon: '<i class="fas fa-fire"></i>'},
choiceB : {name:"Speed", icon:'<i class="fas fa-tachometer-alt"></i>'},
choiceC: {name:"Being Stared at", icon:'<i class="fas fa-eye"></i>'},
choiceD: {name:"Flying", icon:'<i class="fas fa-plane-departure"></i>'},
correct:"B",
},
{ phobia : "Technophobia",
choiceA : {name:"Kissing", icon:'<i class="far fa-kiss"></i>'},
choiceB : {name:"School", icon:'<i class="fas fa-school"></i>'},
choiceC: {name:"Technology", icon:'<i class="fas fa-sim-card"></i>'},
choiceD: {name:"Love", icon:'<i class="far fa-heart"></i>'},
correct:"C",
},
{ phobia : "Tonitrophobia",
choiceA : {name:"Spiders", icon:'<i class="fas fa-spider"></i>'},
choiceB : {name:"Women", icon:'<i class="fas fa-female"></i>'},
choiceC: {name:"Being Stared at", icon:'<i class="fas fa-eye"></i>'},
choiceD: {name:"Thunder", icon:'<i class="fas fa-cloud-showers-heavy"></i>'},
correct:"D",
},
{ phobia : "Trypanophobia",
choiceA : {name:"Injections", icon:'<i class="fas fa-syringe"></i>'},
choiceB : {name:"Rain", icon:'<i class="fas fa-cloud-rain"></i>'},
choiceC: {name:"Fire", icon: '<i class="fas fa-fire"></i>'},
choiceD: {name:"Women", icon:'<i class="fas fa-female"></i>'},
correct:"A",
},
{ phobia : "Verminophobia",
choiceA : {name:"Women", icon:'<i class="fas fa-female"></i>'},
choiceB : {name:"Germs", icon:'<i class="fas fa-viruses"></i>'},
choiceC: {name:"Fire", icon: '<i class="fas fa-fire"></i>'},
choiceD: {name:"Houses", icon:'<i class="fas fa-home"></i>'},
correct:"B",
},
{ phobia : "Wiccaphobia ",
choiceA : {name:"Needles", icon:'<i class="fas fa-syringe"></i>'},
choiceB : {nname:"School", icon:'<i class="fas fa-school"></i>'},
choiceC: {name:"Witches", icon:'<i class="fas fa-hat-wizard"></i>'},
choiceD: {name:"Kissing", icon:'<i class="far fa-kiss"></i>'},
correct:"C",
}
]