let questions= [
    { phobia : "Aerophobia",
        choiceA : {name:"Flying", icon:'<i class="fas fa-plane"></i>'},
        choiceB : {name:"Amphibians", icon:'<i class="fas fa-frog"></i>'},
        choiceC : {name:"Insects", icon:'<i class="fas fa-bug"></i>'},
        choiceD : {name:"Being touched", icon:'<i class="fas fa-hand-paper"></i>'},
        correct:"A",
        answer:"FLYING"
},
{ phobia : "Arachnophobia",
choiceA : {name:"Horses", icon:'<i class="fas fa-horse"></i>'},
choiceB : {name:"Spiders", icon:'<i class="fas fa-spider"></i>'},
choiceC: {name:"Technology", icon:'<i class="fas fa-sim-card"></i>'},
choiceD: {name:"Trees", icon:'<i class="fas fa-tree"></i>'},
correct:"B",
answer: "SPIDERS"
}, 
{ phobia : "Aichmophobia",
choiceA : {name:"Books", icon:'<i class="fas fa-book-open"></i>'},
choiceB : {name:"Doctors", icon:'<i class="fas fa-user-md"></i>'},
choiceC: {name:"Needles", icon:'<i class="fas fa-syringe"></i>'},
choiceD: {name:"Buttons", icon :'<i class="fas fa-toggle-on"></i>'},
correct:"C",
answer: "NEEDLES"
},
{ phobia : "Androphobia",
choiceA : {name:"Dentists", icon:'<i class="fas fa-tooth"></i>'},
choiceB : {name:"Insects", icon:'<i class="fas fa-bug"></i>'},
choiceC: {name:"Witches", icon:'<i class="fas fa-hat-wizard"></i>'},
choiceD: {name:"Men", icon:'<i class="fas fa-male"></i>'},
correct:"D",
answer: "MEN"
},
{ phobia : "Anthrophobia",
choiceA : {name:"Flowers", icon:'<i class="fas fa-spa"></i>'},
choiceB : {name:"Trees", icon:'<i class="fas fa-tree"></i>'},
choiceC: {name:"Technology", icon:'<i class="fas fa-sim-card"></i>'},
choiceD: {name:"Computers", icon:'<i class="fas fa-desktop"></i>'},
correct:"A",
answer: "FLOWERS"
},
{ phobia : "Anthropophobia",
choiceA : {name:"Flowers", icon:'<i class="fas fa-spa"></i>'},
choiceB : {name:"People", icon:'<i class="fas fa-users"></i>'},
choiceC: {name:"Injections", icon:'<i class="fas fa-syringe"></i>'},
choiceD: {name:"Blood", icon:'<i class="fas fa-tint"></i>'},
correct : "B",
answer: "PEOPLE"
},
{ phobia : "Aphenphosmphobia",
choiceA : {name:"Horses", icon:'<i class="fas fa-horse"></i>'},
choiceB : {name:"Buttons", icon :'<i class="fas fa-toggle-on"></i>'},
choiceC: {name:"Being touched", icon:'<i class="fas fa-hand-paper"></i>'},
choiceD: {name:"Germs", icon:'<i class="fas fa-viruses"></i>'},
correct: "C",
answer: "BEING TOUCHED"
},
{ phobia : "Astraphobia",
choiceA : {name:"Dogs", icon:'<i class="fas fa-dog"></i>'},
choiceB : {name:"Insects", icon:'<i class="fas fa-bug"></i>'},
choiceC: {name:"Flying", icon:'<i class="fas fa-plane"></i>'},
choiceD: {name:"Thunder and Lightening", icon:'<i class="fas fa-bolt"></i>'},
correct:"D",
answer: "THUNDER AND LIGHTENING"
},
{ phobia : "Bacteriophobia ",
choiceA : {name:"Bacteria", icon:'<i class="fas fa-bacterium"></i>'},
choiceB : {name:"Cats", icon:'<i class="fas fa-cat"></i>'},
choiceC: {name:"Witches", icon:'<i class="fas fa-hat-wizard"></i>'},
choiceD: {name:"Ugliness", icon:'<i class="fas fa-frown-open"></i>'},
correct:"A",
answer: "BACTERIA"
},
{ phobia : "Batrachophobia",
choiceA : {name:"Technology", icon:'<i class="fas fa-sim-card"></i>'},
choiceB : {name:"Amphibians", icon:'<i class="fas fa-frog"></i>'},
choiceC: {name:"Speed", icon:'<i class="fas fa-tachometer-alt"></i>'},
choiceD: {name:"Bacteria", icon:'<i class="fas fa-bacterium"></i>'},
correct:"B",
answer: "AMPHIBIANS"
},
{ phobia : "Bibliophobia",
choiceA : {name:"Clocks", icon:'<i class="far fa-clock"></i>'},
choiceB : {name:"Blood", icon:'<i class="fas fa-tint"></i>'},
choiceC: {name:"Books", icon:'<i class="fas fa-book-open"></i>'},
choiceD: {name:"Germs", icon:'<i class="fas fa-viruses"></i>'},
correct:"C",
answer: "BOOKS"
},
{ phobia : "Botanophobia",
choiceA : {name:"Dentists", icon:'<i class="fas fa-tooth"></i>'},
choiceB : {name:"The Colour White", icon:'<i class="far fa-square"></i>'},
choiceC: {name:"Speed", icon:'<i class="fas fa-tachometer-alt"></i>'},
choiceD: {name:"Plants", icon:'<i class="fas fa-seedling"></i>'},
correct:"D",
answer: "PLANTS"
},
{ phobia : "Cacophobia",
choiceA : {name:"Ugliness", icon:'<i class="fas fa-frown-open"></i>'},
choiceB : {name:"Computers", icon:'<i class="fas fa-desktop"></i>'},
choiceC: {name:"Ferns", icon:'<i class="fab fa-pagelines"></i>'},
choiceD: {name:"Amphibians", icon:'<i class="fas fa-frog"></i>'},
correct:"A",
answer: "UGLINESS"
},
{ phobia : "Chionophobia",
choiceA : {name:"Doctors", icon:'<i class="fas fa-user-md"></i>'},
choiceB : {name:"Snow", icon:'<i class="fas fa-snowflake"></i>'},
choiceC: {name:"The Moon", icon:'<i class="far fa-moon"></i>'},
choiceD: {name:"Ugliness", icon:'<i class="fas fa-frown-open"></i>'},
correct:"B",
answer: "SNOW"
},
{ phobia : "Chronomentrophobia",
choiceA : {name:"Blood", icon:'<i class="fas fa-tint"></i>'},
choiceB : {name:"Injections", icon:'<i class="fas fa-syringe"></i>'},
choiceC: {name:"Clocks", icon:'<i class="far fa-clock"></i>'},
choiceD: {name:"The Colour White", icon:'<i class="far fa-square"></i>'},
correct:"C",
answer: "CLOCKS"
},
{ phobia : "Cyberphobia",
choiceA : {name:"Snow", icon:'<i class="fas fa-snowflake"></i>'},
choiceB : {name:"Children", icon:'<i class="fas fa-child"></i>'},
choiceC: {name:"Men", icon:'<i class="fas fa-male"></i>'},
choiceD: {name:"Computers", icon:'<i class="fas fa-desktop"></i>'},
correct:"D",
answer: "COMPUTERS"
},
{ phobia : "Cynophobia",
choiceA : {name:"Dogs", icon:'<i class="fas fa-dog"></i>'},
choiceB : {name:"Water", icon:'<i class="fas fa-water"></i>'},
choiceC: {name:"Birds", icon:'<i class="fas fa-crow"></i>'},
choiceD: {name:"Trees", icon:'<i class="fas fa-tree"></i>'},
correct:"A",
answer: "DOGS"
},
{ phobia : "Dendrophobia",
choiceA : {name:"Children", icon:'<i class="fas fa-child"></i>'},
choiceB : {name:"Trees", icon:'<i class="fas fa-tree"></i>'},
choiceC: {name:"School", icon:'<i class="fas fa-school"></i>'},
choiceD: {name:"Dentists", icon:'<i class="fas fa-tooth"></i>'},
correct:"B",
answer: "TREES"
},
{ phobia : "Dentophobia",
choiceA : {name:"Plants", icon:'<i class="fas fa-seedling"></i>'},
choiceB : {name:"Speed", icon:'<i class="fas fa-tachometer-alt"></i>'},
choiceC: {name:"Dentists", icon:'<i class="fas fa-tooth"></i>'},
choiceD: {name:"Flying", icon:'<i class="fas fa-plane"></i>'},
correct:"C",
answer: "DENTISTS"
},
{ phobia : "Domatophobia",
choiceA : {name:"Being touched", icon:'<i class="fas fa-hand-paper"></i>'},
choiceB : {name:"Dogs", icon:'<i class="fas fa-dog"></i>'},
choiceC: {name:"People", icon:'<i class="fas fa-users"></i>'},
choiceD: {name:"Houses", icon:'<i class="fas fa-home"></i>'},
correct:"D",
answer: "HOUSES"
},

{ phobia : "Elurophobia",
choiceA : {name:"Cats", icon:'<i class="fas fa-cat"></i>'},
choiceB : {name:"Doctors", icon:'<i class="fas fa-user-md"></i>'},
choiceC: {name:"Ferns", icon:'<i class="fab fa-pagelines"></i>'},
choiceD: {name:"Bacteria", icon:'<i class="fas fa-bacterium"></i>'},
correct:"A",
answer: "CATS"
},
{ phobia : "Entomophobia",
choiceA : {name:"Horses", icon:'<i class="fas fa-horse"></i>'},
choiceB : {name:"Insects", icon:'<i class="fas fa-bug"></i>'},
choiceC: {name:"Birds", icon:'<i class="fas fa-crow"></i>'},
choiceD: {name:"The Sun", icon:'<i class="fas fa-sun"></i>'},
correct:"B",
answer: "INSECTS"
},
{ phobia : "Equinophobia",
choiceA : {name:"Water", icon:'<i class="fas fa-water"></i>'},
choiceB : {name:"Marraige", icon:'<i class="fas fa-ring"></i>'},
choiceC: {name:"Horses", icon:'<i class="fas fa-horse"></i>'},
choiceD: {name:"The Moon", icon:'<i class="far fa-moon"></i>'},
correct:"C",
answer: "HORSES"
},
{ phobia : "Gamophobia",
choiceA : {name:"Books", icon:'<i class="fas fa-book-open"></i>'},
choiceB : {name:"Cats", icon:'<i class="fas fa-cat"></i>'},
choiceC: {name:"Birds", icon:'<i class="fas fa-crow"></i>'},
choiceD: {name:"Marraige", icon:'<i class="fas fa-ring"></i>'},
correct:"D",
answer: "MARRAIGE"
},
{ phobia : "Gynophobia",
choiceA : {name:"Women", icon:'<i class="fas fa-female"></i>'},
choiceB : {name:"Children", icon:'<i class="fas fa-child"></i>'},
choiceC: {name:"The Colour Black", icon:'<i class="fas fa-square"></i>'},
choiceD: {name:"Amphibians", icon:'<i class="fas fa-frog"></i>'},
correct:"A",
answer: "women",
},
{ phobia : "Heliophobia ",
choiceA : {name:"Plants", icon:'<i class="fas fa-seedling"></i>'},
choiceB : {name:"The Sun", icon:'<i class="fas fa-sun"></i>'},
choiceC: {name:"Injections", icon:'<i class="fas fa-syringe"></i>'},
choiceD: {name:"Men", icon:'<i class="fas fa-male"></i>'},
correct:"B",
answer: "THE SUN"
},
{ phobia : "Hemophobia",
choiceA : {name:"Ferns", icon:'<i class="fab fa-pagelines"></i>'},
choiceB : {name:"Spiders", icon:'<i class="fas fa-spider"></i>'},
choiceC: {name:"Blood", icon:'<i class="fas fa-tint"></i>'},
choiceD: {name:"The Colour White", icon:'<i class="far fa-square"></i>'},
correct:"C",
answer: "BLOOD"
},
{ phobia : "Hydrophobia",
choiceA : {name:"Being touched", icon:'<i class="fas fa-hand-paper"></i>'},
choiceB : {name:"Sleep", icon:'<i class="fas fa-bed"></i>'},
choiceC: {name:"People", icon:'<i class="fas fa-users"></i>'},
choiceD: {name:"Water", icon:'<i class="fas fa-water"></i>'},
correct:"D",
answer: "WATER"
},
{ phobia : "Iatrophobia",
choiceA : {name:"Doctors", icon:'<i class="fas fa-user-md"></i>'},
choiceB : {name:"Marraige", icon:'<i class="fas fa-ring"></i>'},
choiceC: {name:"Snow", icon:'<i class="fas fa-snowflake"></i>'},
choiceD: {name:"Needles", icon:'<i class="fas fa-syringe"></i>'},
correct:"A",
answer: "DOCTORS"
},
{ phobia : "Koumpounophobia",
choiceA : {name:"The Sun", icon:'<i class="fas fa-sun"></i>'},
choiceB : {name:"Buttons", icon :'<i class="fas fa-toggle-on"></i>'},
choiceC: {name:"The Colour Black", icon:'<i class="fas fa-square"></i>'},
choiceD: {name:"Plants", icon:'<i class="fas fa-seedling"></i>'},
correct:"B",
answer: "BUTTONS"
},
{ phobia : "Leukophobia",
choiceA : {name:"The Sun", icon:'<i class="fas fa-sun"></i>'},
choiceB : {name:"Flying", icon:'<i class="fas fa-plane-departure"></i>'},
choiceC: {name:"The Colour White", icon:'<i class="far fa-square"></i>'},
choiceD: {name:"Thunder", icon:'<i class="fas fa-cloud-showers-heavy"></i>'},
correct:"C",
answer: "THE COLOUR WHITE"
},
{ phobia : "Megalophobia",
choiceA : {name:"Bacteria", icon:'<i class="fas fa-bacterium"></i>'},
choiceB : {name:"The Colour Black", icon:'<i class="fas fa-square"></i>'},
choiceC: {name:"Water", icon:'<i class="fas fa-water"></i>'},
choiceD: {name:"Large Things", icon:'<i class="fas fa-search-plus"></i>'},
correct:"D",
answer: "LARGE THINGS"
},
{ phobia : "Melanophobia ",
choiceA : {name:"The Colour Black", icon:'<i class="fas fa-square"></i>'},
choiceB : {name:"Houses", icon:'<i class="fas fa-home"></i>'},
choiceC: {name:"Germs", icon:'<i class="fas fa-head-side-cough"></i>'},
choiceD: {name:"Books", icon:'<i class="fas fa-book-open"></i>'},
correct:"A",
answer: "THE COLOUR BLACK"
},
{ phobia : "Microphobia ",
choiceA : {name:"Kissing", icon:'<i class="far fa-kiss"></i>'},
choiceB : {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
choiceC: {name:"Sleep", icon:'<i class="fas fa-bed"></i>'},
choiceD: {name:"Snow", icon:'<i class="fas fa-snowflake"></i>'},
correct:"B",
answer: "SMALL THINGS"
},
{ phobia : "Mysophobia",
choiceA : {name:"Ugliness", icon:'<i class="fas fa-frown-open"></i>'},
choiceB : {name:"Flying", icon:'<i class="fas fa-plane-departure"></i>'},
choiceC: {name:"Germs", icon:'<i class="fas fa-head-side-cough"></i>'},
choiceD: {name:"Marraige", icon:'<i class="fas fa-ring"></i>'},
correct:"C",
answer: "GERMS"
},
{ phobia : "Noctiphobia",
choiceA : {name:"Thunder", icon:'<i class="fas fa-cloud-showers-heavy"></i>'},
choiceB : {name:"Flying", icon:'<i class="fas fa-plane"></i>'},
choiceC: {name:"Large Things", icon:'<i class="fas fa-search-plus"></i>'},
choiceD: {name:"Night", icon:'<i class="fas fa-moon"></i>'},
correct:"D",
answer: "NIGHT"
},

{ phobia : "Nosocomephobia",
choiceA : {name:"Hospitals", icon:'<i class="fas fa-hospital"></i>'},
choiceB : {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
choiceC: {name:"Thunder and Lightening", icon:'<i class="fas fa-bolt"></i>'},
choiceD: {name:"Germs", icon:'<i class="fas fa-head-side-cough"></i>'},
correct:"A",
answer: "HOSPITALS"
},
{ phobia : "Ombrophobia",
choiceA : {name:"Disease", icon:'<i class="fas fa-disease"></i>'},
choiceB : {name:"Rain", icon:'<i class="fas fa-cloud-rain"></i>'},
choiceC: {name:"Dogs", icon:'<i class="fas fa-dog"></i>'},
choiceD: {name:"Men", icon:'<i class="fas fa-male"></i>'},
correct:"B",
answer: "RAIN"
},
{ phobia : "Ornithophobia",
choiceA : {name:"Horses", icon:'<i class="fas fa-horse"></i>'},
choiceB : {name:"Being Stared at", icon:'<i class="fas fa-eye"></i>'},
choiceC: {name:"Birds", icon:'<i class="fas fa-crow"></i>'},
choiceD: {name:"Large Things", icon:'<i class="fas fa-search-plus"></i>'},
correct:"C",
answer: "BIRDS"
},
{ phobia : "Papyrophobia",
choiceA : {name:"People", icon:'<i class="fas fa-users"></i>'},
choiceB : {name:"Disease", icon:'<i class="fas fa-disease"></i>'},
choiceC: {name:"Cats", icon:'<i class="fas fa-cat"></i>'},
choiceD: {name:"Paper", icon:'<i class="far fa-sticky-note"></i>'},
correct:"D",
answer: "PAPER"
},
{ phobia : "Pathophobia",
choiceA : {name:"Disease", icon:'<i class="fas fa-disease"></i>'},
choiceB : {name:"Night", icon:'<i class="fas fa-moon"></i>'},
choiceC: {name:"Computers", icon:'<i class="fas fa-desktop"></i>'},
choiceD: {name:"Clocks", icon:'<i class="far fa-clock"></i>'},
correct:"A",
answer: "DISEASE"
},
{ phobia : "Pedophobia",
choiceA : {name:"Paper", icon:'<i class="far fa-sticky-note"></i>'},
choiceB : {name:"Children", icon:'<i class="fas fa-child"></i>'},
choiceC: {name:"Halloween", icon:'<i class="fas fa-ghost"></i>'},
choiceD: {name:"Flowers", icon:'<i class="fas fa-spa"></i>'},
correct:"B",
answer: "CHILDREN"
},
{ phobia : "Philematophobia ",
choiceA : {name:"Spiders", icon:'<i class="fas fa-spider"></i>'},
choiceB : {name:"Love", icon:'<i class="far fa-heart"></i>'},
choiceC: {name:"Kissing", icon:'<i class="far fa-kiss"></i>'},
choiceD: {name:"Sleep", icon:'<i class="fas fa-bed"></i>'},
correct:"C",
answer: "KISSING",
},
{ phobia : "Philophobia",
choiceA : {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
choiceB : {name:"Kissing", icon:'<i class="far fa-kiss"></i>'},
choiceC: {name:"Germs", icon:'<i class="fas fa-head-side-cough"></i>'},
choiceD: {name:"Love", icon:'<i class="far fa-heart"></i>'},
correct:"D",
answer: "LOVE"
},
{ phobia : "Podophobia",
choiceA : {name:"Feet", icon:'<i class="fas fa-socks"></i>'},
choiceB : {name:"The Moon", icon:'<i class="far fa-moon"></i>'},
choiceC: {name:"Halloween", icon:'<i class="fas fa-ghost"></i>'},
choiceD: {name:"Clocks", icon:'<i class="far fa-clock"></i>'},
correct:"A",
answer: "FEET"
},
{ phobia : "Pteridophobia",
choiceA : {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
choiceB : {name:"Ferns", icon:'<i class="fab fa-pagelines"></i>'},
choiceC: {name:"Halloween", icon:'<i class="fas fa-ghost"></i>'},
choiceD: {name:"Houses", icon:'<i class="fas fa-home"></i>'},
correct:"B",
answer: "FERNS"
},
{ phobia : "Pteromerhanophobia",
choiceA : {name:"Thunder and Lightening", icon:'<i class="fas fa-bolt"></i>'},
choiceB : {name:"Feet", icon:'<i class="fas fa-socks"></i>'},
choiceC: {name:"Flying", icon:'<i class="fas fa-plane-departure"></i>'},
choiceD: {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
correct:"C",
answer: "FLYING"
},
{ phobia : "Pyrophobia",
choiceA : {name:"Paper", icon:'<i class="far fa-sticky-note"></i>'},
choiceB : {name:"Needles", icon:'<i class="fas fa-syringe"></i>'},
choiceC: {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
choiceD: {name:"Fire", icon: '<i class="fas fa-fire"></i>'},
correct:"D",
answer: "FIRE"
},
{ phobia : "Samhainophobia",
choiceA : {name:"Halloween", icon:'<i class="fas fa-ghost"></i>'},
choiceB : {name:"Rain", icon:'<i class="fas fa-cloud-rain"></i>'},
choiceC: {name:"Feet", icon:'<i class="fas fa-socks"></i>'},
choiceD: {name:"Night", icon:'<i class="fas fa-moon"></i>'},
correct:"A",
answer: "HALLOWEEN"
},
{ phobia : "Scolionophobia",
choiceA : {name:"Germs", icon:'<i class="fas fa-viruses"></i>'},
choiceB : {name:"School", icon:'<i class="fas fa-school"></i>'},
choiceC: {name:"Disease", icon:'<i class="fas fa-disease"></i>'},
choiceD: {name:"Buttons", icon :'<i class="fas fa-toggle-on"></i>'},
correct:"B",
answer: "SCHOOL"
},
{ phobia : "Scoptophobia",
choiceA : {name:"Thunder", icon:'<i class="fas fa-cloud-showers-heavy"></i>'},
choiceB : {name:"Horses", icon:'<i class="fas fa-horse"></i>'},
choiceC: {name:"Being Stared at", icon:'<i class="fas fa-eye"></i>'},
choiceD: {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
correct:"C",
answer: "BEING STARED AT"
},
{ phobia : "Selenophobia",
choiceA : {name:"Paper", icon:'<i class="far fa-sticky-note"></i>'},
choiceB : {name:"Feet", icon:'<i class="fas fa-socks"></i>'},
choiceC: {name:"Flowers", icon:'<i class="fas fa-spa"></i>'},
choiceD: {name:"The Moon", icon:'<i class="far fa-moon"></i>'},
correct:"D",
answer: "THE MOON"
},
{ phobia : "Somniphobia",
choiceA : {name:"Sleep", icon:'<i class="fas fa-bed"></i>'},
choiceB : {name:"Love", icon:'<i class="far fa-heart"></i>'},
choiceC: {name:"Halloween", icon:'<i class="fas fa-ghost"></i>'},
choiceD: {name:"Rain", icon:'<i class="fas fa-cloud-rain"></i>'},
correct:"A",
answer: "SLEEP"
},
{ phobia : "Tachophobia",
choiceA : {name:"Fire", icon: '<i class="fas fa-fire"></i>'},
choiceB : {name:"Speed", icon:'<i class="fas fa-tachometer-alt"></i>'},
choiceC: {name:"Being Stared at", icon:'<i class="fas fa-eye"></i>'},
choiceD: {name:"Flying", icon:'<i class="fas fa-plane-departure"></i>'},
correct:"B",
answer: "SPEED"
},
{ phobia : "Technophobia",
choiceA : {name:"Kissing", icon:'<i class="far fa-kiss"></i>'},
choiceB : {name:"School", icon:'<i class="fas fa-school"></i>'},
choiceC: {name:"Technology", icon:'<i class="fas fa-sim-card"></i>'},
choiceD: {name:"Love", icon:'<i class="far fa-heart"></i>'},
correct:"C",
answer: "TECHNOLOGY"
},
{ phobia : "Tonitrophobia",
choiceA : {name:"Spiders", icon:'<i class="fas fa-spider"></i>'},
choiceB : {name:"Women", icon:'<i class="fas fa-female"></i>'},
choiceC: {name:"Being Stared at", icon:'<i class="fas fa-eye"></i>'},
choiceD: {name:"Thunder", icon:'<i class="fas fa-cloud-showers-heavy"></i>'},
correct:"D",
answer: "THUNDER"
},
{ phobia : "Trypanophobia",
choiceA : {name:"Injections", icon:'<i class="fas fa-syringe"></i>'},
choiceB : {name:"Rain", icon:'<i class="fas fa-cloud-rain"></i>'},
choiceC: {name:"Fire", icon: '<i class="fas fa-fire"></i>'},
choiceD: {name:"Women", icon:'<i class="fas fa-female"></i>'},
correct:"A",
answer: "INJECTIONS"
},
{ phobia : "Verminophobia",
choiceA : {name:"Women", icon:'<i class="fas fa-female"></i>'},
choiceB : {name:"Germs", icon:'<i class="fas fa-viruses"></i>'},
choiceC: {name:"Fire", icon: '<i class="fas fa-fire"></i>'},
choiceD: {name:"Houses", icon:'<i class="fas fa-home"></i>'},
correct:"B",
answer: "GERMS"
},
{ phobia : "Wiccaphobia ",
choiceA : {name:"Needles", icon:'<i class="fas fa-syringe"></i>'},
choiceB : {name:"School", icon:'<i class="fas fa-school"></i>'},
choiceC: {name:"Witches", icon:'<i class="fas fa-hat-wizard"></i>'},
choiceD: {name:"Kissing", icon:'<i class="far fa-kiss"></i>'},
correct:"C",
answer: "WITCHES"
},
{ phobia : "Ablutophobia",
choiceA : {name:"Washing", icon:'<i class="fas fa-bath"></i>'},
choiceB : {name:"Accidents", icon:'<i class="fas fa-car-crash"></i>'},
choiceC : {name:"Music", icon:'<i class="fas fa-music"></i>'},
choiceD : { name:"Ugliness", icon:'<i class="fas fa-frown-open"></i>'},
correct:"A",
answer:"WASHING"
},
{ phobia : "Acousticophobia",
choiceA : {name:"Music", icon:'<i class="fas fa-music"></i>'},
choiceB : {name:"Noise", icon:'<i class="fas fa-bullhorn"></i>'},
choiceC: {name:"Marraige", icon:'<i class="fas fa-ring"></i>'},
choiceD: {name:"Guitars", icon:'<i class="fas fa-guitar"></i>'},
correct:"B",
answer: "NOISE"
}, 
{ phobia : "Agyrophobia",
choiceA : {name:"Letters", icon:'<i class="fas fa-mail-bulk"></i>'},
choiceB : {name:"Anchors", icon:'<i class="fas fa-anchor"></i>'},
choiceC: {name:"Streets", icon:'<i class="fas fa-road"></i>'},
choiceD: { name:"Clocks", icon:'<i class="far fa-clock"></i>'},
correct:"C",
answer: "STREETS"
},
{ phobia : "Ambulophobia",
choiceA : {name:"Riding in a car", icon:'<i class="fas fa-car"></i>'},
choiceB : {name:"Ambulances", icon: '<i class="fas fa-ambulance"></i>'},
choiceC: { name:"Children", icon:'<i class="fas fa-child"></i>'},
choiceD: {name:"Walking", icon:'<i class="fas fa-walking"></i>'},
correct:"D",
answer: "WALKING"
},
{ phobia : "Amaxophobia",
choiceA : {name:"Riding in a car", icon:'<i class="fas fa-car"></i>'},
choiceB : {name:"Cake", icon:'<i class="fas fa-birthday-cake"></i>'},
choiceC: { name:"People", icon:'<i class="fas fa-users"></i>'},
choiceD: { name:"Large Things", icon:'<i class="fas fa-search-plus"></i>'},
correct:"A",
answer: "RIDING IN A CAR"
},
{ phobia : "Angrophobia",
choiceA : {name:"Flowers", icon:'<i class="fas fa-spa"></i>'},
choiceB : {name:"Being angry", icon:'<i class="far fa-angry"></i>'},
choiceC: {name:"Pins", icon:'<i class="fas fa-thumbtack"></i>'},
choiceD: {name:"Going to Bed", icon:'<i class="fas fa-bed"></i>'},
correct : "B",
answer: "BEING ANGRY"
},
{ phobia : "Astrophobia",
choiceA : {name:"Thunder and Lightening", icon:'<i class="fas fa-bolt"></i>'},
choiceB : { name:"Amphibians", icon:'<i class="fas fa-frog"></i>'},
choiceC: {name:"Stars", icon:'<i class="far fa-star"></i>'},
choiceD: { name:"Flying", icon:'<i class="fas fa-plane"></i>'},
correct: "C",
answer: "STARS"
},
{ phobia : "Enetophobia",
choiceA : {name:"Insects", icon:'<i class="fas fa-bug"></i>'},
choiceB : {name:"Music", icon:'<i class="fas fa-music"></i>'},
choiceC: { name:"Rain", icon:'<i class="fas fa-cloud-rain"></i>'},
choiceD: {name:"Pins", icon:'<i class="fas fa-thumbtack"></i>'},
correct:"D",
answer: "PINS"
},
{ phobia : "Bufonophobia",
choiceA : {name:"Toads", icon:'<i class="fas fa-frog"></i>'},
choiceB : {name:"Cleanliness", icon: '<i class="fas fa-hand-sparkles"></i>'},
choiceC : {name:"Being Happy", icon:' <i class="far fa-smile-beam"></i>'},
choiceD : { name:"Being touched", icon:'<i class="fas fa-hand-paper"></i>'},
correct:"A",
 answer:"TOADS"
},
{ phobia : "Cathisophobia",
choiceA : { name:"Cleanliness", icon: '<i class="fas fa-hand-sparkles"></i>'},
choiceB : {name:"Sitting", icon:'<i class="fas fa-couch"></i>'},
choiceC: {name:"Cake", icon:'<i class="fas fa-birthday-cake"></i>'},
choiceD: {name:"Cats", icon:'<i class="fas fa-cat"></i>'},
correct:"B",
answer: "SITTING"
}, 
{ phobia : "Chirophobia",
choiceA : {name:"Feet", icon:'<i class="fas fa-socks"></i>'},
choiceB : {name:"Cheese", icon:'<i class="fas fa-cheese"></i>'},
choiceC: {name:"Hands", icon:'<i class="fas fa-road"></i>'},
choiceD: {name:"Buttons", icon :'<i class="fas fa-toggle-on"></i>'},
correct:"C",
answer: "HANDS"
},
{ phobia : "Chrometophobia",
choiceA : { name:"Clocks", icon:'<i class="far fa-clock"></i>'},
choiceB : {name:"Colours ", icon:'<i class="fas fa-palette"></i>'},
choiceC: { name:"Snow", icon:'<i class="fas fa-snowflake"></i>'},
choiceD: {name:"Money", icon:'<i class="fas fa-dollar-sign"></i>'},
correct:"D",
answer: "MONEY"
},
{ phobia : "Cibophobia",
choiceA : {name:"Food", icon:'<i class="fas fa-hamburger"></i>'},
choiceB : {name:"Work", icon:'<i class="fas fa-wrench"></i>'},
choiceC : {name:"Snow", icon:'<i class="fas fa-snowflake"></i>'},
choiceD: { name:"Dogs", icon:'<i class="fas fa-dog"></i>'},
correct:"A",
answer: "FOOD"
},
{ phobia : "Clinophobia",
choiceA : {name:"Flowers", icon:'<i class="fas fa-spa"></i>'},
choiceB : {name:"Going to Bed", icon:'<i class="fas fa-bed"></i>'},
choiceC: {name:"Snow", icon:'<i class="fas fa-snowflake"></i>'},
choiceD: {name:"Clocks", icon:'<i class="far fa-clock"></i>'},
correct : "B",
answer: "GOING TO BED"
},
{ phobia : "Cryophobia",
choiceA : {name:"Thunder and Lightening", icon:'<i class="fas fa-bolt"></i>'},
choiceB : {name:"Being Sad", icon :'<i class="far fa-sad-tear"></i>'},
choiceC: {name:"Ice", icon:'<i class="fas fa-icicles"></i>'},
choiceD: {name:"Dogs", icon:'<i class="fas fa-dog"></i>'},
correct: "C",
answer: "ICE"
},
{ phobia : "Kymophobia",
choiceA : {name:"Buttons", icon :'<i class="fas fa-toggle-on"></i>'},
choiceB : {name:"Cats", icon:'<i class="fas fa-cat"></i>'},
choiceC: {name:"Kissing", icon:'<i class="far fa-kiss"></i>'},
choiceD: {name:"Waves", icon:'<i class="fas fa-water"></i>'},
correct:"D",
answer: "WAVES"
},
{ phobia : "Dikephobia",
choiceA : {name:"Justice", icon:'<i class="fas fa-balance-scale-right"></i>'},
choiceB : { name:"ferns", icon:'<i class="fab fa-pagelines"></i>'},
choiceC : {name:"Puzzles", icon:' <i class="fas fa-puzzle-piece"></i>'},
choiceD : { name:"Injections", icon:'<i class="fas fa-syringe"></i>'},
correct:"A",
answer:"JUSTICE"
},
{ phobia : "Dinophobia",
choiceA : { name:"Sleep", icon:'<i class="fas fa-bed"></i>'},
choiceB : {name:"Dizziness", icon:'<i class="far fa-dizzy"></i>'},
choiceC: { name:"Witches", icon:'<i class="fas fa-hat-wizard"></i>'},
choiceD: {name:"Trees", icon:'<i class="fas fa-tree"></i>'},
correct:"B",
answer: "DIZZINESS"
}, 
{ phobia : "Dextrophobia",
choiceA : {name:"Cake", icon:'<i class="fas fa-birthday-cake"></i>'},
choiceB : {name:"Doctors", icon:'<i class="fas fa-user-md"></i>'},
choiceC: {name:"Objects to your Right", icon:'<i class="far fa-hand-point-right"></i>'},
choiceD: {name:"Justice", icon:'<i class="fas fa-balance-scale-right"></i>'},
correct:"C",
answer: "OBJECTS TO YOUR RIGHT"
},
{ phobia : "Dystychiphobia",
choiceA : {name:"Puzzles", icon:' <i class="fas fa-puzzle-piece"></i>'},
choiceB : {name:"Disease", icon:'<i class="fas fa-disease"></i>'
},
choiceC: { name:"Doctors", icon:'<i class="fas fa-user-md"></i>'},
choiceD: {name:"Accidents", icon:'<i class="fas fa-car-crash"></i>'},
correct:"D",
answer: "ACCIDENTS"
},
{ phobia : "Ereuthrophobia",
choiceA : {name:"Blushing", icon:'<i class="far fa-flushed"></i>'},
choiceB : {name:"Electricity", icon:'<i class="fas fa-plug"></i>'},
choiceC: {name:"Blood", icon:'<i class="fas fa-tint"></i>'},
choiceD: {name:"Cats", icon:'<i class="fas fa-cat"></i>'
},
correct:"A",
answer: "BLUSHING"
},
{ phobia : "Geumaphobia",
choiceA : {name:"Germs", icon:'<i class="fas fa-viruses"></i>'},
choiceB : {name:"Taste", icon:'<i class="far fa-grin-tongue"></i>'},
choiceC: {name:"Fish", icon:'<i class="fas fa-fish"></i>'},
choiceD: { name:"Marraige", icon:'<i class="fas fa-ring"></i>'
},
correct : "B",
answer: "TASTE"
},
{ phobia : "Glossophobia",
choiceA : { name:"Taste", icon:'<i class="far fa-grin-tongue"></i>'},
choiceB : { name:"Vegetables", icon:'<i class="fas fa-carrot"></i>'},
choiceC: {name:"Public Speaking", icon:'<i class="fas fa-chalkboard-teacher"></i>'},
choiceD: {name:"The Sun", icon:'<i class="fas fa-sun"></i>'
},
correct: "C",
answer: "PUBLIC SPEAKING"
},
{ phobia : "Homichlophobia",
choiceA : {name:"Men", icon:'<i class="fas fa-male"></i>'},
choiceB : {name:"Blood", icon:'<i class="fas fa-tint"></i>'},
choiceC: { name:"Being touched", icon:'<i class="fas fa-hand-paper"></i>'
},
choiceD: {name:"Fog", icon:'<i class="fas fa-smog"></i>'},
correct:"D",
answer: "FOG"
},
{ phobia : "Ichthyophobia",
        choiceA : {name:"Fish", icon:'<i class="fas fa-fish"></i>'},
        choiceB : {name:"Cheese", icon:'<i class="fas fa-cheese"></i>'},
        choiceC : {name:"Taste", icon:'<i class="far fa-grin-tongue"></i>'},
        choiceD : {name:"Ice", icon:'<i class="fas fa-icicles"></i>'},
        correct:"A",
        answer:"FISH"
},
{ phobia : "Iophobia",
choiceA : {name:"Lorries", icon:' <i class="fas fa-truck-moving"></i>'},
choiceB : {name:"Poison", icon:'<i class="fas fa-skull-crossbones"></i>'},
choiceC: { name:"Vegetables", icon:'<i class="fas fa-carrot"></i>'},
choiceD: {name:"Cats", icon:'<i class="fas fa-cat"></i>'},
correct:"B",
answer: "POISON"
}, 
{ phobia : "Lachanophobia",
choiceA : {name:"Feet", icon:'<i class="fas fa-socks"></i>'},
choiceB : {name:"Work", icon:'<i class="fas fa-wrench"></i>'},
choiceC: {name:"Vegetables", icon:'<i class="fas fa-carrot"></i>'},
choiceD: {name:"Getting Injured", icon :'<i class="fas fa-user-injured"></i>'},
correct:"C",
answer: "VEGETABLES"
},
{ phobia : "Levophobia",
choiceA : {name:"Otters", icon:'<i class="fas fa-otter"></i>'},
choiceB : {name:"Colours ", icon:'<i class="fas fa-palette"></i>'},
choiceC: { name:"The Colour White", icon:'<i class="far fa-square"></i>'},
choiceD: {name:"Objects on your Left", icon:'<i class="far fa-hand-point-left"></i>'},
correct:"D",
answer: "OBJECTS ON YOUR LEFT"
},
{ phobia : "Ligyrophobia",
choiceA : {name:"Loud Noises", icon:'<i class="fas fa-volume-up"></i>'},
choiceB : {name:"Getting Injured", icon:'<i class="fas fa-user-injured"></i>'},
choiceC: {name:"Otters", icon:'<i class="fas fa-otter"></i>'},
choiceD: {name:"Houses", icon:'<i class="fas fa-home"></i>'
},
correct:"A",
answer: "LOUD NOISES"
},
{ phobia : "Lutraphobia",
choiceA : {name:"Flowers", icon:'<i class="fas fa-spa"></i>'},
choiceB : {name:"Otters", icon:'<i class="fas fa-otter"></i>'},
choiceC: {name:"Lorries", icon:' <i class="fas fa-truck-moving"></i>'},
choiceD: {name:"Objects on your Left", icon:'<i class="far fa-hand-point-left"></i>'},
correct : "B",
answer: "OTTERS"
},
{ phobia : "Nephophobia",
choiceA : {name:"Rain", icon:'<i class="fas fa-cloud-rain"></i>'},
choiceB : {name:"Hospitals", icon:'<i class="fas fa-hospital"></i>'},
choiceC: {name:"Clouds", icon:'<i class="fas fa-cloud"></i>'},
choiceD: { name:"Halloween", icon:'<i class="fas fa-ghost"></i>'
},
correct: "C",
answer: "CLOUDS"
},
{ phobia : "Ochlophobia",
choiceA : {name:"Being Sad", icon:'<i class="far fa-sad-cry"></i>'},
choiceB : {name:"Otters", icon:'<i class="fas fa-otter"></i>'},
choiceC: {name:"Being Stared at", icon:'<i class="fas fa-eye"></i>'},
choiceD: {name:"Crowds", icon:'<i class="fas fa-users"></i>'},
correct:"D",
answer: "CROWDS"
},
{ phobia : "Phasmophobia",
choiceA : {name:"Ghosts", icon:'<i class="fas fa-ghost"></i>'},
choiceB : { name:"Blood", icon:'<i class="fas fa-tint"></i>'},
choiceC : { name:"Speed", icon:'<i class="fas fa-tachometer-alt"></i>'},
choiceD : { name:"Plants", icon:'<i class="fas fa-seedling"></i>'},
correct:"A",
answer:"GHOSTS"
},
{ phobia : "Phengophobia",
choiceA : {name:"Swimming", icon:'<i class="fas fa-swimmer"></i>'},
choiceB : {name:"Sunshine", icon:'<i class="fas fa-sun"></i>'},
choiceC: {name:"ferns", icon:'<i class="fab fa-pagelines"></i>'},
choiceD: {name:"Night", icon:'<i class="fas fa-moon"></i>'},
correct:"B",
answer: "SUNSHINE"
}, 
{ phobia : "Pteronophobia",
choiceA : {name:"Books", icon:'<i class="fas fa-book-open"></i>'},
choiceB : {name:"Doctors", icon:'<i class="fas fa-user-md"></i>'},
choiceC: {name:"Streets", icon:'<i class="fas fa-road"></i>'},
choiceD: {name:"Being Tickled by Feathers", icon :'<i class="fas fa-feather-alt"></i>'},
correct:"C",
answer: "BEING TICKLED BY FEATHERS"
},
{ phobia : "Siderodromophobia",
choiceA : {name:"Being Sad", icon:'<i class="far fa-sad-cry"></i>'},
choiceB : {name:"Paper", icon:'<i class="far fa-sticky-note"></i>'},
choiceC: { name:"Objects to your Right", icon:'<i class="far fa-hand-point-right"></i>'},
choiceD: {name:"Trains", icon:'<i class="fas fa-subway"></i>'},
correct:"D",
answer: "TRAINS"
},
{ phobia : "Sitophobia",
choiceA : {name:"Eating", icon:'<i class="fas fa-utensils"></i>'},
choiceB : {name:"Scissors", icon:' <i class="fas fa-cut"></i>'},
choiceC: {name:"Clothing", icon:' <i class="fas fa-tshirt"></i>'},
choiceD: {name:"Feet", icon:'<i class="fas fa-socks"></i>'},
correct:"A",
answer: "EATING"
},
{ phobia : "Sophophobia",
choiceA: { name:"Sitting", icon:'<i class="fas fa-couch"></i>'},
chioceB: {name:"Learning", icon:'<i class="fab fa-leanpub"></i>'},
choiceC: {name:"Love", icon:'<i class="far fa-heart"></i>'},
choiceD: {name:"Small Things", icon:'<i class="fas fa-search-minus"></i>'},
correct : "B",
answer: "BEING ANGRY"
},
{ phobia : "Staurophobia",
choiceA : {name:"Thunder and Lightening", icon:'<i class="fas fa-bolt"></i>'},
choiceB : {name:"Scissors", icon :' <i class="fas fa-cut"></i>'},
choiceC: {name:"Crosses", icon:'<i class="fas fa-cross"></i>'},
choiceD: {name:"Stars", icon:'<i class="far fa-star"></i>'},
correct: "C",
answer: "CROSSES"
},
{ phobia : "Thalassophobia",
choiceA : {name:"Spa Treatments", icon:'<i class="fas fa-spa"></i>'},
choiceB : {name:"Theatres", icon:'<i class="fas fa-theater-masks"></i>'},
choiceC: {name:"Swimming", icon:'<i class="fas fa-swimmer"></i>'},
choiceD: {name:"The Sea", icon:'<i class="fas fa-water"></i>'},
correct:"D",
answer: "THE SEA"
},
{ phobia : "Thermophobia",
choiceA: {name: "Heat", icon:'<i class="fas fa-thermometer-full"></i>'},
choiceB: {name:"Pizza", icon:'<i class="fas fa-pizza-slice"></i>'},
choiceC: {name:"Clothing", icon:'<i class="fas fa-tshirt"></i>'},
choiceD: {name:"Poison", icon:'<i class="fas fa-skull-crossbones"></i>'},
correct:"A",answer:"HEAT"
}
];