let questions= [
    { phobia : "Aerophobia",
        choiceA : {name:"Flying", icon:'<i class="fas fa-plane"></i>'},
        choiceB : {name:"", icon:""},
        choiceC : {name:"", icon:""},
        choiceD : {name:"", icon:""},
        correct :"A",
},
{ phobia : "Arachnophobia",
choiceA : {name:"", icon:""},
choiceB : {name:"Spiders", icon:'<i class="fas fa-spider"></i>'},
choiceC: {name:"", icon:""},
choiceD: {name:"", icon:""},
correct:"B",
}, 
{ phobia : "Aichmophobia",
choiceA : {name:"", icon:""},
choiceB : {name:"", icon:""},
choiceC: {name:"Needles", icon:'<i class="fas fa-syringe"></i>'},
choiceD: {name:"", icon:""},
correct:"C",
},
{ phobia : "Androphobia",
choiceA : {name:"", icon:""},
choiceB : {name:"", icon:""},
choiceC: {name:"", icon:""},
choiceD: {name:"Men", icon:'<i class="fas fa-male"></i>'},
correct:"D",
},
{ phobia : "Anthrophobia",
choiceA : {name:"Flowers", icon:'<i class="fas fa-spa"></i>'},
choiceB : {name:"", icon:""},
choiceC: {name:"", icon:""},
choiceD: {name:"", icon:""},
correct:"A",
},
{ phobia : "Anthropophobia",
choiceA : {name:"", icon:""},
choiceB : {name:"People", icon:'<i class="fas fa-users"></i>'},
choiceC: {name:"", icon:""},
choiceD: {name:"", icon:""},
correct:"B",
},
{ phobia : "Aphenphosmphobia",
choiceA : {name:"", icon:""},
choiceB : {name:"", icon:""},
choiceC: {name:"Being touched", icon:'<i class="fas fa-hand-paper"></i>'},
choiceD: {name:"", icon:""},
correct:"C"
},
{ phobia : "Astraphobia",
choiceA : {name:"", icon:""},
choiceB : {name:"", icon:""},
choiceC: {name:"", icon:""},
choiceD: {name:"Thunder and Lightening", icon:'<i class="fas fa-bolt"></i>'},
correct:"D",
},
{ phobia : "Bacteriophobia ",
choiceA : {name:"Bacteria", icon:'<i class="fas fa-bacterium"></i>'},
choiceB : {name:"", icon:""},
choiceC: {name:"", icon:""},
choiceD: {name:"", icon:""},
correct:"A",
},
{ phobia : "Batrachophobia",
choiceA : {name:"", icon:""},
choiceB : {name:"Amphibians", icon:'<i class="fas fa-frog"></i>'},
choiceC: {name:"", icon:""},
choiceD: {name:"", icon:""},
correct:"B",
},
{ phobia : "Bibliophobia",
choiceA : {name:"", icon:""},
choiceB : {name:"", icon:""},
choiceC: {name:"Books", icon:'<i class="fas fa-book-open"></i>'},
choiceD: {name:"", icon:""},
correct:"C",
},
{ phobia : "Botanophobia",
choiceA : {name:"", icon:""},
choiceB : {name:"", icon:""},
choiceC: {name:"", icon:""},
choiceD: {name:"Plants", icon:'<i class="fas fa-seedling"></i>'},
correct:"D",
},
{ phobia : "Cacophobia",
choiceA : {name:"Ugliness", icon:'<i class="fas fa-frown-open"></i>'},
choiceB : {name:"", icon:""},
choiceC: {name:"", icon:""},
choiceD: {name:"", icon:""},
correct:"A",
},
{ phobia : "Chionophobia",
choiceA : {name:"", icon:''},
choiceC: {name:"", icon:""},
choiceD: {name:"", icon:""},
correct:"B",
},
{ phobia : "Chronomentrophobia",
choiceA : {name:"", icon:""},
choiceB : {name:"", icon:""},
choiceC: {name:"Clocks", icon:'<i class="far fa-clock"></i>'},
choiceD: {name:"", icon:""},
correct:"C",
},
{ phobia : "Cyberphobia",
choiceA : {name:"", icon:""},
choiceB : {name:"", icon:""},
choiceC: {name:"", icon:""},
choiceD: {name:"Computers", icon:'<i class="fas fa-desktop"></i>'},
correct:"D",
},
{ phobia : "Cynophobia",
choiceA : {name:"Dogs", icon:'<i class="fas fa-dog"></i>'},
choiceB : {name:"", icon:""},
choiceC: {name:"", icon:""},
choiceD: {name:"", icon:""},
correct:"A",
}
]